# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08my.proto\x12\x04game\"(\n\x05\x43olor\x12\t\n\x01r\x18\x01 \x01(\x05\x12\t\n\x01g\x18\x02 \x01(\x05\x12\t\n\x01\x62\x18\x03 \x01(\x05\"Z\n\rServerMessage\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0e\n\x06header\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x1a\n\x05\x63olor\x18\x04 \x01(\x0b\x32\x0b.game.Color\"\xdc\x01\n\x0bPlayerInput\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64irection_x\x18\x02 \x01(\x02\x12\x13\n\x0b\x64irection_y\x18\x03 \x01(\x02\x12\r\n\x05shoot\x18\x04 \x01(\x08\x12\x19\n\x11target_position_x\x18\x05 \x01(\x02\x12\x19\n\x11target_position_y\x18\x06 \x01(\x02\x12\x0c\n\x04name\x18\x07 \x01(\t\x12\x1a\n\x05\x63olor\x18\x08 \x01(\x0b\x32\x0b.game.Color\x12\x0f\n\x07respawn\x18\t \x01(\x08\x12\x0f\n\x07message\x18\n \x01(\t\"\x9a\x01\n\x06Player\x12\n\n\x02id\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\n\n\x02hp\x18\x04 \x01(\x02\x12\x10\n\x08last_hit\x18\x05 \x01(\t\x12\n\n\x02vx\x18\x06 \x01(\x02\x12\n\n\x02vy\x18\x07 \x01(\x02\x12\x0c\n\x04name\x18\x08 \x01(\t\x12\x0e\n\x06max_hp\x18\t \x01(\x02\x12\x1a\n\x05\x63olor\x18\n \x01(\x0b\x32\x0b.game.Color\"B\n\x06\x42ullet\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\n\n\x02vx\x18\x04 \x01(\x02\x12\n\n\x02vy\x18\x05 \x01(\x02\"L\n\x10LeaderboardEntry\x12\x1a\n\x05\x63olor\x18\x01 \x01(\x0b\x32\x0b.game.Color\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06points\x18\x03 \x01(\x05\"\xd5\x01\n\tGameState\x12\x1d\n\x07players\x18\x01 \x03(\x0b\x32\x0c.game.Player\x12\x1d\n\x07\x62ullets\x18\x02 \x03(\x0b\x32\x0c.game.Bullet\x12\x10\n\x08map_size\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x12\n\nserver_fps\x18\x05 \x01(\x05\x12+\n\x0bleaderboard\x18\x06 \x03(\x0b\x32\x16.game.LeaderboardEntry\x12$\n\x07message\x18\x07 \x01(\x0b\x32\x13.game.ServerMessageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'my_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COLOR._serialized_start=18
  _COLOR._serialized_end=58
  _SERVERMESSAGE._serialized_start=60
  _SERVERMESSAGE._serialized_end=150
  _PLAYERINPUT._serialized_start=153
  _PLAYERINPUT._serialized_end=373
  _PLAYER._serialized_start=376
  _PLAYER._serialized_end=530
  _BULLET._serialized_start=532
  _BULLET._serialized_end=598
  _LEADERBOARDENTRY._serialized_start=600
  _LEADERBOARDENTRY._serialized_end=676
  _GAMESTATE._serialized_start=679
  _GAMESTATE._serialized_end=892
# @@protoc_insertion_point(module_scope)
